version: '3'

env:
  DOCKER_ADDR: docker-local.home.com

  REPO_USER: admin
  REPO_PASSWORD: $REPO_PWD 

  RELEASE_VERSION: 0.1

includes:

  #使用子目录为根目录
  console:
    taskfile: ./console/Taskfile.yml
    dir: ./console

  query-api:
    taskfile: ./query-api/Taskfile.yml
    dir: ./query-api


## Build all docker images and then upload them to remote repository
tasks:
  build:
    desc: build docker images
    deps:
      - task: console:docker
      - task: query-api:local_docker
  push_docker:
    desc: push docker tasks
    deps:
      - task: console:push_docker
      - task: query-api:push_docker
    cmds:
      - echo "Congratulations, all tasks finished and the corresponding images are pushed"
