### create a site
POST http://localhost:8080/sites
content-type: application/json

{
  "name": "nsf",
  "displayName": "nsf图书馆",
  "crawlerType": 3,
  "attributes": {
    "siteUrl": "https://www.nosadfun.com"
  }
}


### Create a catalog
POST http://localhost:8080/catalogs
content-type: application/json

{
  "siteId": "64ea11b58b1f9d5c2e308b8a",
  "name": "武侠",
  "url": "https://www.nosadfun.com/category/8/",
  "crawlerType": 3
}


### submit a task running for catalog page
POST http://localhost:8080/tasks/catalog-pages
Content-Type: application/json

{
  "catalogId": "64f308e4eddbeeaa4bb06c01",
  "url": "https://www.nosadfun.com/category/2/1-5.html"
}


### submit a novel task
POST http://localhost:8080/tasks/novels
Content-Type: application/json

{
  "catalogId": "64ea12bb8b1f9d5c2e308b8b",
  "url": "https://www.nosadfun.com/book/229662/catalog/"
}
