spring:
  data:
    mongodb:
      database: books
      host: 192.168.1.11
      port: 30018
      username: db_user
      password: db_pwd
      authentication-database: admin

    redis:
      host: 192.168.1.11
      port: 30084
      password: kmhfZFWfzRWeHri
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
          enabled: true

  cache:
    redis:
      time-to-live: 60000
      cache-null-values: true
      key-prefix: "${spring.application.name}:"
#      password:
