spring:
  data:
    mongodb:
      database: books
      host: localhost
      port: 27017
      username: db_user
      password: db_pwd
      authentication-database: admin

    redis:
      host: localhost
      port: 6379
      password: pwd
      #      host: 10.0.10.11
      #      port: 32477
      #      password: db_pwd
      #cluster:
      #nodes:
      #- localhost:7000
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
          enabled: true

  cache:
    redis:
      time-to-live: 60000
      cache-null-values: true
      key-prefix: "${spring.application.name}:"
#      password:
