version: '3'

#  includes:

env:
  QUERY_IMAGE: '{{ .DOCKER_ADDR }}/query-api:{{ .RELEASE_VERSION }}'

tasks:
  local_docker: #使用本地的可执行文件编译Docker
    desc: locally build a docker image after code compiled
    cmds:
      - task: build
      - task: docker

  build:
    desc: build a executable file
    cmds:
      - gradle clean build -x test

  clean:
    cmds:
      - gradle clean

  docker:
    desc: build a docker image
    deps: [ build ]
    cmds:
      - docker build -f Dockerfile  -t $QUERY_IMAGE --rm ./

  push_docker:
    desc: tag the existing docker image and push it into remote repository
    deps: [ docker ]
    cmds:
#      - docker login $DOCKER_ADDR -u $REPO_USER -p $REPO_PASSWORD
      - docker push $QUERY_IMAGE